services:
  - type: web
    name: flask-backend
    env: python
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "bash backend/start.sh"
    plan: free
    autoDeploy: true

    